apiVersion: v1
kind: PersistentVolume
metadata:
  name: fourfridays-pv
  annotations:
    pv.kubernetes.io/provisioned-by: blockvolume.csi.oraclecloud.com
spec:
  storageClassName: oci-bv
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  csi:
    driver: blockvolume.csi.oraclecloud.com
    fsType: ext4
    volumeHandle: ocid1.volume.oc1.iad.aaaaaaaaaa