apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: traefik-claim
spec:
  volumeName: fourfridays-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: oci-bv