additionalArguments:
  - --certificatesresolvers.le.acme.email=hello@fourfridays.com
  - --certificatesresolvers.le.acme.storage=/ssl-cert/acme.json
  - --certificatesresolvers.le.acme.tlschallenge=true
  - --certificatesresolvers.le.acme.dnschallenge.resolvers=1.1.1.1:53,8.8.8.8:53

ports:
  web:
    redirectTo: websecure

persistence:
  enabled: true
  path: /ssl-cert

initContainers:
  - name: volume-permissions
    image: busybox:1.31.1
    command: ["sh", "-c", "chmod -Rv 600 /ssl-cert/*"]
    volumeMounts:
      - name: ssl-cert
        mountPath: /ssl-cert

podSecurityContext:
  fsGroup: null

ingressRoute:
  dashboard:
    enabled: true

securityContext:
  readOnlyRootFilesystem: false
  runAsGroup: 0
  runAsUser: 0
  runAsNonRoot: false

service:
  enabled: true
  type: LoadBalancer
  annotations: {
    oci.oraclecloud.com/load-balancer-type: "lb",
    service.beta.kubernetes.io/oci-load-balancer-shape: "flexible",
    service.beta.kubernetes.io/oci-load-balancer-shape-flex-min: "10",
    service.beta.kubernetes.io/oci-load-balancer-shape-flex-max: "10"
  }
  spec: {
  }